# Generated by Django 5.2 on 2025-04-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_data", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
