# Generated by Django 5.1.7 on 2025-04-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_mines',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='Easy', max_length=6),
        ),
        migrations.AddField(
            model_name='game',
            name='grid_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='mine_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
